### Post create new Patients
POST http://localhost:4000/api/v1/patients
Content-Type: application/json

{
  "name": "sam Juma",
  "email": "",
  "address": "Springfield, IL",
  "dateOfBirth": "2017-07-15",
  "registrationDate": "2025-11-03"
}