### Post create new Patients
POST http://localhost:4000/api/v1/patients
Content-Type: application/json

{
  "name": "Hassan Jason",
  "email": "Drulo@gmail.com",
  "address": "Moyale Vile, IL",
  "dateOfBirth": "03-05-2010",
  "registrationDate": "03-11-2012"
}