### PUT request to Update Patient details
PUT http://localhost:4000/api/v1/patients/10
Content-Type: application/json

{
  "name": "zeinab Hassan",
  "email": "zeinab67@gmail.com",
  "address": "Nairobi Vile, IL",
  "dateOfBirth": "03-05-2017",
  "registrationDate": "03-11-2018"
}